; HEADER_BLOCK_START
; generated by SnapmakerOrca 2.3.5 on 2026-08-27 at 21:00:00
; total layer number: 42
; model printing time: 6m 12s; total estimated time: 11m 55s
; HEADER_BLOCK_END

; EXECUTABLE_BLOCK_START
G90
M83
G1 X10 Y10 F3000
T0
G1 E5 F1200
; EXECUTABLE_BLOCK_END

; filament used [mm] = 322.58,0.00,0.00,0.00
; filament used [cm3] = 0.79,0.00,0.00,0.00
; filament used [g] = 1.00,0.00,0.00,0.00
; total filament used [g] = 1.00
; total filament cost = 0.03
; CONFIG_BLOCK_START
; filament_colour = #FFFFFF;#000000;#FF0000;#00FF00
; filament_density = 1.27,1.25,1.24,1.24
; filament_diameter = 1.75,1.75,1.75,1.75
; filament_settings_id = "Generic PETG @BBL A1M";"Bambu PETG-CF";"Generic PLA";"Generic PLA"
; filament_type = PETG;PETG-CF;PLA;PLA
; filament_vendor = "Generic";"Bambu Lab";"Generic";"Generic"
; printer_model = Bambu Lab A1 mini
; printer_settings_id = "Bambu Lab A1 mini 0.4 nozzle"
; print_settings_id = "0.20mm Standard @BBL A1M"
; single_extruder_multi_material = 1
; CONFIG_BLOCK_END
