; HEADER_BLOCK_START
; generated by SnapmakerOrca 2.3.5 on 2026-08-27 at 19:42:11
; total layer number: 128
; model printing time: 2h 14m 3s; total estimated time: 2h 21m 40s
; HEADER_BLOCK_END

; EXECUTABLE_BLOCK_START
G90
M83
G1 X10 Y10 F3000
T0
G1 E5 F1200
T2
G1 E5 F1200
; EXECUTABLE_BLOCK_END

; filament used [mm] = 4821.33,0.00,1290.44,0.00
; filament used [cm3] = 11.60,0.00,3.11,0.00
; filament used [g] = 14.38,0.00,3.98,0.00
; total filament used [g] = 18.36
; total filament used for wipe tower [g] = 1.24
; total filament cost = 0.46
; CONFIG_BLOCK_START
; filament_colour = #FF6A13;#FFFFFF;#1A1A1A;#00A3E0
; filament_density = 1.24;1.24;1.27;1.24
; filament_diameter = 1.75;1.75;1.75;1.75
; filament_settings_id = "Snapmaker PLA Orange";"Generic PLA";"Generic PETG @U1";"Generic PLA"
; filament_type = PLA;PLA;PETG;PLA
; filament_vendor = "Snapmaker";"Generic";"Generic";"Generic"
; filament_map = 1;2;3;4
; printer_model = Snapmaker U1
; printer_settings_id = "Snapmaker U1 (0.4 nozzle)"
; print_settings_id = "0.20 Strength @Snapmaker U1 (0.4 nozzle)"
; CONFIG_BLOCK_END
