; HEADER_BLOCK_START
; generated by SnapmakerOrca 2.3.5 on 2026-08-27 at 20:05:00
; total layer number: 41
; HEADER_BLOCK_END
G90
M83
G1 E5 F1200
; filament used [mm] = 2100.50
; filament used [cm3] = 5.05
; filament used [g] = 6.27
; total filament used [g] = 6.27
; total filament cost = 0.16
; CONFIG_BLOCK_START
; filament_colour = #1A1A1A
; filament_density = 1.24
; filament_settings_id = "Generic PLA"
; filament_type = PLA
; filament_vendor = "Generic"
; printer_model = Snapmaker U1
; CONFIG_BLOCK_END
